version: 2
updates:
  - package-ecosystem: pip
    directory: /hometunnel-client/rootfs/opt/hometunnel
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /hometunnel-client
    schedule:
      interval: weekly
